modLoader="javafml"
loaderVersion="[43,]"
license="GNU_GPL.3"
issueTrackerURL="https://github.com/toadie-odie/TodeCoins/issues"

[[mods]]
modId="todecoins"
version="1.19.2-1.0.0"
displayName="Tode Coins"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/toadie-odie/TodeCoins"
logoFile="logo.png"
credits="Special thanks to my sons, whom I homeschool, and Marshal Nash for supporting all the projects I tend to get myself into!"
authors="Warren Tode (ToadieOdie)"
description="Adds currency, a banker and leprechaun villager with trades, armor and potions to the game."

[[dependencies.todecoins]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.todecoins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.backpacked]
    catalogueItemIcon="todecoins:copper_coin" #Support for Catalogue mod
